###
POST http://localhost:3001/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "Jacky",
    "email": "jacky@gmail.com",
    "password": "987654321"
}

###
GET http://localhost:3001/api/users HTTP/1.1

###
GET http://localhost:3001/api/users/636b12b5feaf44053e84b8a0 HTTP/1.1

###
PUT http://localhost:3001/api/users/636b12b5feaf44053e84b8a0 HTTP/1.1
Content-Type: application/json

{
    "name": "Mario Alzate",
    "email": "mario@gmail.com",
    "password": "159753"
}

### 
DELETE  http://localhost:3001/api/users/636b1327feaf44053e84b8a3 HTTP/1.1